exclude: migrations|^(static/|logs)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        rev: 22.1.0
        exclude: migrations
        additional_dependencies:
          - "click==8.0.4"
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: ["-iii", "-ll"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ['--ignore=SIM115, E501']
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args:
          [
            "--load-plugins=pylint_django",
            "--django-settings-module=config.settings",
            "--disable=C0111",
            "--disable=W0613",
            "--disable=W0511",
          ]
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: django-tests
        name: django-tests
        entry: ./manage.py test --settings=config.settings.test
        language: system
        types: [python]
        pass_filenames: false
